import CorporateForm from "@/app/components/CorporateForm/CorporateForm"
import Image from 'next/image';
import vatregimg from '../../../../public/icons/corporate-icons/vat.png';
import vatregimg1 from './images/vat-reg-uae-dubai.png';
import { IoMdCheckboxOutline } from "react-icons/io";
import VatDocModal from "./VatDocModal";
import DistinctVatRegModal from "./DistinctVatRegModal";
import ElvBrandRepModal from "./ElvBrandRepModal";
import ExpNewBusinessAvenuesModal from "./ExpNewBusinessAvenuesModal";
import EnhCashFlowModal from "./EnhCashFlowModal";
import { BsCheck2Square } from "react-icons/bs";
const VatRegistrationCnt = () => {
  return (
    <>
    <div className="vat-reg-sec1">
                <div className="container">
                    <div className="row">
                        <div className="col-md-12 col-lg-6 col-xl-6 col-sm-12 col-xs-12">
                            <h1 className="vat-reg-hd">VAT Registration Services in Dubai, UAE</h1>
                            <p>No matter the size of your business, it's crucial to register for VAT in UAE to comply with Emirati laws. This VAT registration process in UAE denotes that your business is recognized by the Government and is compliant with regulations. VAT registration in UAE is income-based and varies depending on the revenue generated by your business.</p>
                            <p>VAT registration is not only about compliance but also offers various advantages to businesses operating in the UAE. Registered businesses can collect VAT from their customers, which is then paid to the government. However, they can also claim input tax credit, which allows them to recover the VAT paid on their business expenses. This mechanism can significantly improve a business's cash flow and overall financial health.</p>
                            <p>Furthermore, being VAT-registered can boost a business's reputation, signaling to customers and partners that the business operates transparently and in accordance with the country's legal framework. This can be especially important when dealing with other registered businesses or government entities, as it demonstrates a commitment to professionalism and accountability.</p>
                        </div>
                        <div className="col-md-12 col-lg-6 col-xl-6 col-sm-12 col-xs-12">
                            <Image src={vatregimg1} className="vat-reg-img" />
                        </div>
                    </div>
                </div>
            </div>

            <div className="vat-reg-sec2">
                <div className="container">
                    <div className="row">
                        <div className="col-md-12 col-lg-6 col-xl-6 col-sm-12 col-xs-12">
                            <h2 className="vat-reg-hd">Types of VAT registration</h2>
                            <p>When applying for VAT registration services, businesses must choose between two categories based on their annual turnover. The categories available for VAT registration are as follows:</p>
                            <div className="vat-reg-chkbox-blk">
                                <div className="vat-reg-chkbox-icon">
                                    <IoMdCheckboxOutline />
                                </div>
                                <div className="vat-reg-chkbox-cnt">
                                    <h6>Mandatory Registration</h6>
                                    <p>A business must register for VAT if its taxable supplies and imports or taxable expenses exceed AED 375,000 during the last 12 months.</p>
                                </div>
                            </div>
                            <div className="vat-reg-chkbox-blk">
                                <div className="vat-reg-chkbox-icon">
                                    <IoMdCheckboxOutline />
                                </div>
                                <div className="vat-reg-chkbox-cnt">
                                    <h6>Voluntary Registration</h6>
                                    <p>It is optional for businesses to apply for registration whose taxable supplies and imports or taxable expenses exceed AED 187,500 but does not exceed AED 375,000 during the last 12 months.</p>
                                </div>
                            </div>

                        </div>
                        <div className="col-md-12 col-lg-6 col-xl-6 col-sm-12 col-xs-12">
                            <h2 className="vat-reg-doc-tlt">Required documents for VAT registration in UAE</h2>
                            <div className="vat-reg-doc-mdl-blk">
                                <div className="vat-reg-doc-img">
                                    <Image src={vatregimg} />
                                </div>
                                <div className="vat-reg-doc-modal">
                                    <VatDocModal/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="vat-reg-sec3">
                <div className="container">
                    <h2 className="vat-reg-hd">Why Should Businesses in the UAE Consider VAT Registration?</h2>
                    <p>For businesses operating in the UAE, considering VAT registration holds significant merit. While some businesses have the option to delay registration until they meet compulsory revenue thresholds, there are a multitude of benefits associated with being VAT registered.</p>
                    <div className="row">
                        <div className="col-md-12 col-lg-3 col-sm-12 col-xl-3 col-xs-12 pl-0 pr-0">
                            <div className="vat-reg-box-bgimg">
                                <div className="vat-reg-box">
                                    <h6>Distinct VAT Registration Number</h6>
                                    <DistinctVatRegModal/>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-12 col-lg-3 col-sm-12 col-xl-3 col-xs-12 pl-0 pr-0">
                            <div className="vat-reg-box-bgimg">
                                <div className="vat-reg-box">
                                    <h6>Elevated Brand Reputation</h6>
                                    <ElvBrandRepModal/>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-12 col-lg-3 col-sm-12 col-xl-3 col-xs-12 pl-0 pr-0">
                            <div className="vat-reg-box-bgimg">
                                <div className="vat-reg-box">
                                    <h6>Exploration of New Business Avenues</h6>
                                    <ExpNewBusinessAvenuesModal/>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-12 col-lg-3 col-sm-12 col-xl-3 col-xs-12 pl-0 pr-0">
                            <div className="vat-reg-box-bgimg">
                                <div className="vat-reg-box">
                                    <h6>Enhanced Cash Flow</h6>
                                    <EnhCashFlowModal/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="vat-reg-sec4">
                <div className="container">
                    <div className="row">
                        <div className="col-md-12 col-lg-8 col-sm-12 col-xl-8 col-xs-12">
                            <h2 className="vat-reg-hd">Why Elevate for VAT registration in UAE?</h2>
                            <p>Elevate Auditing offers top-notch VAT registration services in Dubai,UAE for new businesses which include analyzing your turnover to determine whether your business should register for VAT or wait. We will facilitate the process by applying for online VAT registration and obtaining the Tax Registration Number (TRN) for your company. Additionally, we will ensure that your company's VAT certificate is issued by the FTA.</p>
                            <h3>Our VAT Services include the followings:</h3>
                            <ul>
                                <li><BsCheck2Square/> VAT Registrations</li>
                                <li><BsCheck2Square/> VAT Return filings.</li>
                                <li><BsCheck2Square/> VAT Refunds.</li>
                                <li><BsCheck2Square/> VAT Voluntary disclosure.</li>
                                <li><BsCheck2Square/> VAT Reconsideration.</li>
                                <li><BsCheck2Square/> VAT deregistration service</li>
                                <li><BsCheck2Square/> VAT Audit</li>
                                <li><BsCheck2Square/> Liaison with FTA on their tax-related matters</li>
                            </ul>
                            <h6>Looking to register for VAT in the UAE? Let us help you simplify the process! Contact us today to get started!</h6>
                        </div>
                        <div className="col-md-12 col-lg-4 col-sm-12 col-xl-4 col-xs-12">
                            <CorporateForm/>
                        </div>
                    </div>
                </div>
            </div>
    </>
  )
}

export default VatRegistrationCnt