import ItForm from "@/app/components/WebForm/ItForm"
import SeoAccordian from "./SeoAccordian1"
import Link from 'next/link';
import SeoAccordian1 from "./SeoAccordian1";
import SeoAccordian2 from "./SeoAccordian2";

const SeoCnt = () => {
  return (
    <>
      <div className="seo-1st-blk">
        <div className="container mt-5 mb-5">
          <div className="row">
            <div className="col-md-6 col-xl-8 col-lg-8 col-sm-12 col-xs-12">
              <h1 className="seo-hd">Elevate: Your Premier SEO Agency in London, UK.</h1>
              <h5>Achieve Top Rankings. Dominate the Search Results. Sustain Your Position for Relevant Keywords.</h5>
              <p>Whether your clientele resides around the corner or spans across continents, our SEO Agency in London is dedicated to elevating your online visibility. We specialize in positioning you in front of your target audience, no matter where they are. With a commitment to white hat SEO practices, our skilled professionals ensure that your web pages remain favorably regarded by Google and other prominent search engines. Here at Elevate, as a top SEO agency in London,UK we recognize that a website surpasses its role as a mere digital page. It represents a valuable expanse of virtual real estate. Through meticulous optimization of every pixel within, you can unlock a flood of traffic, converting your website into an enduring conduit for leads.
              </p>
              <p>From meticulous keyword analysis to expansive online outreach, we conduct SEO marketing with an unprecedented finesse, a rarity in today's digital landscape. Our regular progress updates will ensure you're well-informed about the return on investment generated by your expenditures. </p>
            </div>
            <div className="col-md-6 col-xl-4 col-lg-4 col-sm-12 col-xs-12">
              <ItForm />
            </div>
          </div>
        </div>
      </div>

      <div className="seo-pwr-bg">
        <div className="se-sec-2">
          <div className="container">
            <h2 className="seo-subhd">The Power of SEO for Your Business</h2>
            <p className="sec2-p">Amplify Your Business with SEO Services in the UK: Unleash the Potential of Strategic Online Visibility.</p>
            <div className="row">
              <div className="col-md-6 col-lg-3 col-xl-3 col-sm-12 col-xs-12">
                <div className="seo-pwr-box">
                  <h5>Enhanced Visibility</h5>
                  <p>SEO boosts your website's visibility on search engines, with over 75% of users never scrolling past the first page of search results.</p>
                </div>
              </div>
              <div className="col-md-6 col-lg-3 col-xl-3 col-sm-12 col-xs-12">
                <div className="seo-pwr-box">
                  <h5>Increased Organic Traffic</h5>
                  <p>Effective SEO drives organic traffic, generating about 53% of all website traffic.</p>
                </div>
              </div>
              <div className="col-md-6 col-lg-3 col-xl-3 col-sm-12 col-xs-12">
                <div className="seo-pwr-box">
                  <h5>Credibility and Trust</h5>
                  <p>Ranking higher establishes trust; 75% of users trust organic search results over paid ads.</p>
                </div>
              </div>
              <div className="col-md-6 col-lg-3 col-xl-3 col-sm-12 col-xs-12">
                <div className="seo-pwr-box">
                  <h5>ROI and Cost-Effectiveness</h5>
                  <p>SEO offers long-term returns, with 61% of marketers ranking it as a top revenue generator.</p>
                </div>
              </div>
            </div>
            <div className="row sec2-snd-box">
              <div className="col-md-12 col-lg-12 col-xl-12 col-sm-12 col-xs-12">
                <h2 className="seo-subhd">Ignite Your SEO Adventure Today!</h2>
                <p>Unleash your website's untapped power. Connect with our experts and join forces to craft a personalized blueprint for skyrocketing your traffic and captivating your intended audience. Elevate your online presence with our top-notch SEO services in London. Let's make your digital dreams a reality!</p>
                {/* <Link className="sep-sec2-cta-btn" >Schedule a meeting </Link> */}

                <div className="seo-sec2-btn">
                  <Link href="/contact-us" className="btn seo-pwr-cta-btn">Contact us</Link>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="seo-sec-3">
        <div className="seo-sec-inrblk">
          <div className="container">
            <h2 className="seo-subhd">Elevating Your Online Presence with Proven Strategies</h2>
            <p className="seo-subhd-3-p">Boost your digital presence with time-tested methods through the expertise of a leading SEO agency in London, UK. Elevate your online visibility with proven strategies for enhanced reach and engagement.</p>
            <div className="row pt-3 ">
              <div className="col-md-6 col-lg-6 col-xl-6 col-sm-12 col-xs-12">
                {/* SEO Accordian  */}
                <SeoAccordian1 />
              </div>
              <div className="col-md-6 col-lg-6 col-xl-6 col-sm-12 col-xs-12 seo-sec3-rgt-blk">
                <div className="seo-sec3-rgt-blk2">
                  <SeoAccordian2 />
                </div>

              </div>
            </div>
          </div>
          <div className="sec-sec-4 pt-5">
            <div className="container">
              <h3 className="seo-subhd-3">Want to Get Explored by More Clients?</h3>
              <p className="seo-subhd-3-p">Searching for exceptional SEO services? Our distinguished SEO agency in London, UK is your key to unlocking online success. Let's supercharge your digital presence now!</p>
            </div>
            <div className="seo-exp-cta-btn-blk">
              <Link href="/contact-us" className="btn seo-exp-cta-btn">Contact us</Link>
            </div>
          </div>
        </div>
      </div>

    </>
  )
}

export default SeoCnt